apiVersion: v1
kind: Service
metadata:
  name: eks-demo-service
  labels:
    app: awesome-app
spec:
  type: LoadBalancer
  selector:
    app: awesome-app
  ports:
    - port: 80
      targetPort: 8080

