name: 'Deploy to EKS'
on:
    workflow_dispatch:
    push:
        paths:
            - "code/**"
        branches: ["main"]
    pull_request:
        paths:
            - "code/**"
        branches: ["main"]
env:
    EKS_CLUSTER_NAME: awesome-app-cluster
jobs:
    deploy_to_eks:
        name: "Build Docker image and deploy to EKS"
        runs-on: ubuntu-latest
        
        steps:

            
            - name: Set short commit
              id: commit
              uses: prompt/actions-commit-hash@v2

            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{secrets.AWS_REGION}}


            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              
            - name: Build, tag and push Docker Image to ECR
              env:
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY}}
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                IMAGE_TAG: ${{steps.commit.outputs.short}}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            - name: Update Kubeconfig
              run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{secrets.AWS_REGION}}

            - name: Deploy to EKS
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
                IMAGE_TAG: ${{ steps.commit.outputs.short }}
              run: |
                sed -i.bak "s|CONTAINER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" manifests/eks-deployment.yml && \
                kubectl apply -f manifests/eks-deployment.yaml
                kubectl apply -f manifests/eks-service.yaml

            

