name: 'Deploy to EKS'
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    deploy_to_eks:
        name: "Build Docker image and deploy to EKS"
        runs-on: ubuntu-latest
        
        steps:

            
            - name: Set short commit
              id: commit
              uses: prompt/actions-commit-hash@v2

            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{secrets.AWS_REGION}}


            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              
            - name: Build, tag and push Docker Image to ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                IMAGE_TAG: ${{steps.commit.outputs.short}}
              run: |
                docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
                docker push $ECR_REPOSITORY:$IMAGE_TAG

              


            

